---
title: "div 32 fold change"
author: "Kara O'Driscoll"
date: "2024-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

# open files

```{r}
rm(list=objects())
library(tidyverse)
library(stringr)  
library(dplyr) 
library(ggfortify)
library(cowplot)
library(readr)
library(RColorBrewer)


Path_to_working_directory <- "/Users/karaodriscoll/Documents/Lab Masters/fold change div32"
setwd(Path_to_working_directory) #sets directory to location of dataset
#opening dataset 
Name_of_dataset <- gsub(".*/","", Path_to_working_directory)
list_of_files <- list.files(pattern="*.csv")
raw_data <- read_csv(list_of_files, id = "file_name", show_col_types = FALSE)

raw_data$Treatment <- as.factor(raw_data$Treatment) #need to make a factor to plot individual plate colours !!!!

raw_data$Time <- as.factor(raw_data$Time)

raw_data <- raw_data %>%
  mutate(Treatment = fct_relevel(Treatment, "Vehicle", "5-MEO-DMT [0.5 µM]", "Psilocin [1 µM]", "DOI [10 µM]"))

```

raincloud

```{r}
packages <- c("cowplot", "readr", "ggplot2", "dplyr", "lavaan", "Hmisc")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}

# Load packages ----
library(ggplot2)

# Defining the geom_flat_violin function ----
# Note: the below code modifies the
# existing github page by removing a parenthesis in line 50

"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}

geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                             position = "dodge", trim = TRUE, scale = "area",
                             show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}

#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomFlatViolin <-
  ggproto("GeomFlatViolin", Geom,
          setup_data = function(data, params) {
            data$width <- data$width %||%
              params$width %||% (resolution(data$x, FALSE) * 0.9)
            
            # ymin, ymax, xmin, and xmax define the bounding rectangle for each group
            data %>%
              group_by(group) %>%
              mutate(
                ymin = min(y),
                ymax = max(y),
                xmin = x,
                xmax = x + width / 2
              )
          },
          
          draw_group = function(data, panel_scales, coord) {
            # Find the points for the line to go all the way around
            data <- transform(data,
                              xminv = x,
                              xmaxv = x + violinwidth * (xmax - x)
            )
            
            # Make sure it's sorted properly to draw the outline
            newdata <- rbind(
              plyr::arrange(transform(data, x = xminv), y),
              plyr::arrange(transform(data, x = xmaxv), -y)
            )
            
            # Close the polygon: set first and last point the same
            # Needed for coord_polar and such
            newdata <- rbind(newdata, newdata[1, ])
            
            ggplot2:::ggname("geom_flat_violin", GeomPolygon$draw_panel(newdata, panel_scales, coord))
          },
          
          draw_key = draw_key_polygon,
          
          default_aes = aes(
            weight = 1, colour = "grey20", fill = "white", size = 0.5,
            alpha = NA, linetype = "solid"
          ),
          
          required_aes = c("x", "y")
  )
```

just gunna go straight in to fold change

# number of spikes

```{r}
ggplot(raw_data, aes(x = `Treatment`, y = `fold_change_spikes`, colour = `Treatment`, fill = `Treatment`))+
   geom_flat_violin(position = position_nudge(x = .1, y = 0), adjust = 1.5, trim = FALSE, alpha = .5, colour = NA) + #adjust function adjusts the smoothness - make snmaller for less of a smooth curve 
  geom_point(aes(y = `fold_change_spikes`, colour = Treatment), position = position_jitter(width = .15), size = 1, shape = 20)+ 
 geom_boxplot(aes(x = `Treatment`, y = `fold_change_spikes`, fill = `Treatment`), outlier.shape = NA, alpha = .5, width = .1, colour = "black") +
  ylab('fold change Number of Spikes')+
  xlab('Treatment')+
  coord_flip()+
  theme_cowplot()+
  
  guides(fill = FALSE)+
  ggtitle('Number of Spikes 10 days post-treatment')
```

```{r}
model_treatment.1 <- lm(`fold_change_spikes`~ Treatment , data = raw_data) 
 #diagnostic plots

Diagnostic_plot.1 <- autoplot(model_treatment.1, smooth.colour = NA) 
print(Diagnostic_plot.1)


anova(model_treatment.1)

summary(aov(model_treatment.1))
```

no sig

# mfr

```{r}
ggplot(raw_data, aes(x = `Treatment`, y = `fold_change_mfr`, colour = `Treatment`, fill = `Treatment`))+
   geom_flat_violin(position = position_nudge(x = .1, y = 0), adjust = 1.5, trim = FALSE, alpha = .5, colour = NA) + #adjust function adjusts the smoothness - make snmaller for less of a smooth curve 
  geom_point(aes(y = `fold_change_mfr`, colour = Treatment), position = position_jitter(width = .15), size = 1, shape = 20)+ 
 geom_boxplot(aes(x = `Treatment`, y = `fold_change_mfr`, fill = `Treatment`), outlier.shape = NA, alpha = .5, width = .1, colour = "black") +
  ylab('fold change Mean Firing Rate')+
  xlab('Treatment')+
  coord_flip()+
  theme_cowplot()+
  
  guides(fill = FALSE)+
  ggtitle('Mean Firing Rate 10 days post-treatment')
```

```{r}
 model_treatment.3 <- lm(`fold_change_spikes`~ Treatment, data = raw_data) 
 #diagnostic plots

Diagnostic_plot.3 <- autoplot(model_treatment.3, smooth.colour = NA) 
print(Diagnostic_plot.3)


anova(model_treatment.3)

summary(aov(model_treatment.3))
```

no sig for either

# spikes per burst

big inc in these - as in inc wells which have, so will lok at raw data

```{r}
shapiro.test(raw_data$`Number of Spikes per Burst - Avg`) 
```

will convert to log

```{r}
raw_data$Time <- as.factor(raw_data$Time)
raw_data$Treatment <- as.factor(raw_data$Treatment)

data_for_stats.5 <- raw_data %>% 
  drop_na(`Number of Spikes per Burst - Avg`) %>%
  mutate("LogParameter"=log(`Number of Spikes per Burst - Avg`))

model_treatment.5 <- lm(`LogParameter` ~ Treatment * Time, data = data_for_stats.5) 
 #diagnostic plots

Diagnostic_plot.5 <- autoplot(model_treatment.5, smooth.colour = NA) 
print(Diagnostic_plot.5)

anova(model_treatment.5)

summary(aov(model_treatment.5))
```

time sig but not treatment

```{r}
TukeyHSD(aov(model_treatment.5), "Time", ordered = TRUE)

summary(aov(model_treatment.5), test = adjusted(type = "BH"))
```

```{r}
ggplot(data_for_stats.5, aes(x = `Time`, y = `LogParameter`, colour = `Time`, fill = `Time`))+
   geom_flat_violin(position = position_nudge(x = .1, y = 0), adjust = 1.5, trim = FALSE, alpha = .5, colour = NA) + #adjust function adjusts the smoothness - make snmaller for less of a smooth curve 
  geom_point(aes(y = `LogParameter`), position = position_jitter(width = .15), size = 1, shape = 20)+ 
 geom_boxplot(aes(x = `Time`, y = `LogParameter`, fill = `Time`), outlier.shape = NA, alpha = .5, width = .1, colour = "black") +
  ylab('log Spikes per Burst')+
  xlab('Time')+
  coord_flip()+
  theme_cowplot()+
  guides(fill = FALSE)+
  ggtitle('Spikes per Burst 10 days post-treatment')
```

yes as time inc more wells and more spb

but not treatment sig so doooo we even care

# burst freq

```{r}
shapiro.test(raw_data$`Burst Frequency - Avg (Hz)`)
```

```{r}
raw_data.b <- subset(raw_data, raw_data$`Burst Frequency - Avg (Hz)` != 0) #removing NA and values of 0
data_for_stats.7 <- raw_data.b %>% 
  drop_na(`Burst Frequency - Avg (Hz)`) %>%
  mutate("LogParameter"=log(`Burst Frequency - Avg (Hz)`))

model_treatment.7 <- lm(`LogParameter` ~ Treatment * Time, data = data_for_stats.7) 
 #diagnostic plots

Diagnostic_plot.7 <- autoplot(model_treatment.7, smooth.colour = NA) 
print(Diagnostic_plot.7)


anova(model_treatment.7)

summary(aov(model_treatment.7))
```

no sig!

# synch

```{r}
si_data <- raw_data %>%
  drop_na(`fold_change_si`)
```

```{r}
ggplot(si_data, aes(x = `Treatment`, y = `fold_change_si`, colour = `Treatment`, fill = `Treatment`))+
   geom_flat_violin(position = position_nudge(x = .1, y = 0), adjust = 1.5, trim = FALSE, alpha = .5, colour = NA) + #adjust function adjusts the smoothness - make snmaller for less of a smooth curve 
  geom_point(aes(y = `fold_change_si`, colour = Treatment), position = position_jitter(width = .15), size = 1, shape = 20)+ 
 geom_boxplot(aes(x = `Treatment`, y = `fold_change_si`, fill = `Treatment`), outlier.shape = NA, alpha = .5, width = .1, colour = "black") +
  ylab('fold change Synchrony Index')+
  xlab('Treatment')+
  coord_flip()+
  theme_cowplot()+
  guides(fill = FALSE)+
  ggtitle('Synchrony Index 10 days post-treatment')
```

```{r}
model_treatment.9 <- lm(`fold_change_si`~ Treatment , data = si_data) 
 #diagnostic plots

Diagnostic_plot.9 <- autoplot(model_treatment.9, smooth.colour = NA) 
print(Diagnostic_plot.9)


anova(model_treatment.9)

summary(aov(model_treatment.9))
```

no sig
